# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  lane :test do
    scan(scheme: "FlowUs-Dev")
  end

  desc "Push a new beta build to TestFlight from Dev"
  lane :dev_release do
    increment_build_number
    build_app(scheme: "FlowUs-Dev")
    upload_to_testflight
  end

  desc "Push a new beta build to TestFlight from Staging"
  lane :staging_release do
    build_app(scheme: "FlowUs-Staging")
    upload_to_testflight
  end

  desc "Push a new beta build to TestFlight from Production"
  lane :prod_release do
    build_app(scheme: "FlowUs-Production")
    upload_to_testflight
  end
end
